# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: operation_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'operation_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17operation_service.proto\".\n\tOperacion\x12\x0e\n\x06numero\x18\x01 \x01(\t\x12\x11\n\toperacion\x18\x02 \x01(\t\"g\n\x10OperacionRequest\x12\x0c\n\x04num1\x18\x01 \x01(\t\x12\x11\n\toperacion\x18\x02 \x01(\t\x12\x0c\n\x04num2\x18\x03 \x01(\t\x12$\n\x10opts_operaciones\x18\x04 \x03(\x0b\x32\n.Operacion\"#\n\x11OperacionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32I\n\x11\x41ritmeticaService\x12\x34\n\tOperacion\x12\x11.OperacionRequest\x1a\x12.OperacionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'operation_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERACION']._serialized_start=27
  _globals['_OPERACION']._serialized_end=73
  _globals['_OPERACIONREQUEST']._serialized_start=75
  _globals['_OPERACIONREQUEST']._serialized_end=178
  _globals['_OPERACIONRESPONSE']._serialized_start=180
  _globals['_OPERACIONRESPONSE']._serialized_end=215
  _globals['_ARITMETICASERVICE']._serialized_start=217
  _globals['_ARITMETICASERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
