# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: numbers_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'numbers_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15numbers_service.proto\"$\n\x0eNumbersRequest\x12\x12\n\nnum_queues\x18\x01 \x01(\x05\"6\n\x0fNumbersResponse\x12\x0f\n\x07numbers\x18\x01 \x03(\x01\x12\x12\n\npublishers\x18\x04 \x03(\t\"F\n\rResultRequest\x12\x11\n\tuser_addr\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x01\x12\x12\n\nsubscribed\x18\x03 \x03(\t\"\"\n\x0eResultResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x32w\n\x0eNumbersService\x12\x31\n\ngetNumbers\x12\x0f.NumbersRequest\x1a\x10.NumbersResponse\"\x00\x12\x32\n\rreceiveResult\x12\x0e.ResultRequest\x1a\x0f.ResultResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'numbers_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBERSREQUEST']._serialized_start=25
  _globals['_NUMBERSREQUEST']._serialized_end=61
  _globals['_NUMBERSRESPONSE']._serialized_start=63
  _globals['_NUMBERSRESPONSE']._serialized_end=117
  _globals['_RESULTREQUEST']._serialized_start=119
  _globals['_RESULTREQUEST']._serialized_end=189
  _globals['_RESULTRESPONSE']._serialized_start=191
  _globals['_RESULTRESPONSE']._serialized_end=225
  _globals['_NUMBERSSERVICE']._serialized_start=227
  _globals['_NUMBERSSERVICE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
