# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import numbers_service_pb2 as numbers__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in numbers_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NumbersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getNumbers = channel.unary_unary(
                '/NumbersService/getNumbers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=numbers__service__pb2.NumbersResponse.FromString,
                _registered_method=True)
        self.receiveResult = channel.unary_unary(
                '/NumbersService/receiveResult',
                request_serializer=numbers__service__pb2.ResultRequest.SerializeToString,
                response_deserializer=numbers__service__pb2.ResultResponse.FromString,
                _registered_method=True)


class NumbersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getNumbers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def receiveResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NumbersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.getNumbers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=numbers__service__pb2.NumbersResponse.SerializeToString,
            ),
            'receiveResult': grpc.unary_unary_rpc_method_handler(
                    servicer.receiveResult,
                    request_deserializer=numbers__service__pb2.ResultRequest.FromString,
                    response_serializer=numbers__service__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NumbersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('NumbersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NumbersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NumbersService/getNumbers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            numbers__service__pb2.NumbersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def receiveResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NumbersService/receiveResult',
            numbers__service__pb2.ResultRequest.SerializeToString,
            numbers__service__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
